version: 2
updates:
  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
